### ISSUE TITLE
Indexer should fetch RDF labels lazily, in the background.

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria#74] opened 2015-02-17 23:21 UTC
https://github.com/OregonDigital/oregondigital/blob/b847c1e5d653d585b1173ebcc5d4c1111a0fa72e/app/jobs/fetch_all_job.rb#L5

**Comment by acozine** [comment] 2015-02-18 15:35
Is this a duplicate of #5?

**Comment by mark-dce** [comment] 2016-01-13 20:47
Yes, this ticket included more detail though (the link to OregonDigital) and supersedes #5 which has been closed.

**Closed** 2016-05-31 18:41 UTC
