### ISSUE TITLE
Investigate Fedora 4 command line migration tools

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/alexandria#11] opened 2018-02-12 19:30 UTC
**ACCEPTANCE CRITERIA**

- [ ] Be able to export a single item with all its attached binaries from Fedora 4 
- [ ] Be able to import a single item with all its attached binaries to a different instance of Fedora 4 
- [ ] Ensure object appears as expected 
- [ ] Write up documentation 

**Migration Tool FCRepo4**
https://github.com/fcrepo4-labs/fcrepo-import-export

**Comment by val99erie** [comment] 2018-02-13 21:55
This story depends on info from #16.  When do we re-ingest using importers vs porting records straight from fedora.

**Comment by bess** [comment] 2018-02-22 18:59
This will be needed for the Fedora 4 upgrade.

**Comment by val99erie** [comment] 2018-03-02 21:52
I think this story is a duplicate of #35.

**Closed** 2018-03-02 21:53 UTC
